# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83a365f2341015674a926eb25c12ad71b7fcc60863d8dbfae79b216f07e218363391271eb687f7804714419164eff3fd26859823e1c9f24b21a0e0248f43cf36

test:
  secret_key_base: c8809c6bb253d22e7540ef76b3e29a93ea94a900d2d73edea887ceb205b902a85f3cabd811dc804aaa1a91877367f5f0799a7291d86e7e2e5f6506e1a16e4b5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
